### ISSUE TITLE
object: *bytes.Reader in Actual Result

### ISSUE THREAD

**Issue by jaredpricedev** [ansible-lockdown/RHEL8-STIG-Audit#42]
**Describe the Issue**
I am getting "object: *bytes.Reader" on several of the items. I found this github thread:
https://github.com/goss-org/goss/issues/845
and it seems to be linked to version of Goss. I did try to run the version listed in the thread but it still had the same result. I have run the command in the goss yaml and it works fine.

**Expected Behavior**
The actual result would show correctly and have the correct result shown.

**Actual Behavior**
This is happening in several stig items where the actual is showing "object: *bytes.Reader"
```
{
            "duration": 112002,
            "end-time": "2024-04-09T00:16:48.792848267Z",
            "err": null,
            "matcher-result": {
                "actual": "object: *bytes.Reader",
                "expected": [
                    "/.*:PermitUserEnvironment [Nn][Oo]/",
                    "!/.*:PermitUserEnvironment\\s+[Yy][Ee][Ss]/"
                ],
                "extra-elements": null,
                "found-elements": [
                    "!/.*:PermitUserEnvironment\\s+[Yy][Ee][Ss]/"
                ],
                "message": "to have patterns",
                "missing-elements": [
                    "/.*:PermitUserEnvironment [Nn][Oo]/"
                ],
                "transform-chain": null,
                "untransformed-value": null
            },
            "meta": {
                "CCI": "CCI-000366",
                "Cat": 2,
                "Group_Title": "SRG-OS-000480-GPOS-00229",
                "Rule_ID": "SV-230330r646870_rule",
                "STIG_ID": "RHEL-08-010830",
                "Vul_ID": "V-230330"
}
```

**Control(s) Affected**
Here are a couple of them I am having issues with:
RHEL-08-010830
RHEL-08-030000
RHEL-08-030360
RHEL-08-030740
RHEL-08-030560
many more...
**Environment (please complete the following information):**

- branch being used: 3.1.0
- Ansible Version: 2.14.5
- Host Python Version: Python 3.6.8
- Ansible Server Python Version: Python 3.9.16
- Additional Details: 
-    Goss version 0.3.23 and v0.4.4

**Additional Notes**
Anything additional goes here

**Possible Solution**
https://github.com/goss-org/goss/issues/845

**Comment by uk-bolly** [comment]
hi @jaredpricedev 

I will look at this is the issue that was raised last week - https://github.com/ansible-lockdown/RHEL8-STIG-Audit/issues/42 . If we find there once we have an issue we can come back to this issue and provide further information.

thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @jaredpricedev 

Thank you for raising the issue, there are some very very big changes between goss versions, which means it will only run with some versions correctly.
You should be running goss v0.4.4 or greater according to the tag you are referring to from the remediation repository.
This will probalny not run at all well on anything lower due to the changes.

If you could confirm the value of
PermitUserEnvironment in your /etc/ssh/sshd_config file as well.

Many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @jaredpricedev 

There has been a few updates to some of the benchmark branches now and to the remediation itself.. Could you let me know if this resolved your issues?

many thanks

uk-bolly

**Comment by uk-bolly** [comment]
Closing Issue as stale
